# Generated by Django 5.1.7 on 2025-05-24 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзинy', 'verbose_name_plural': 'Корзина'},
        ),
    ]
