# Generated by Django 5.1.7 on 2025-05-24 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_products_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='quantity',
            new_name='quantity',
        ),
    ]
